# Generated by Django 2.2.5 on 2019-10-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191012_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='addition',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large'), ('R', 'Regular')], default='R', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='addition',
            unique_together={('name', 'size')},
        ),
    ]
