# Generated by Django 2.2.5 on 2019-10-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20191012_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large'), ('Regular', 'Regular')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large'), ('Regular', 'Regular')], default='R', max_length=1),
        ),
    ]
