# Generated by Django 2.2.5 on 2019-10-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191014_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large'), ('Regular', 'Regular')], default='R', max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large'), ('Regular', 'Regular')], default='R', max_length=8),
        ),
    ]
