# Generated by Django 2.2.5 on 2019-10-18 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20191017_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'cart_item', 'verbose_name_plural': 'cart_items'},
        ),
        migrations.AlterModelOptions(
            name='itemaddition',
            options={'verbose_name': 'item_addition', 'verbose_name_plural': 'item_additions'},
        ),
        migrations.AlterModelOptions(
            name='itemtopping',
            options={'verbose_name': 'item_topping', 'verbose_name_plural': 'item_toppings'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'order_item', 'verbose_name_plural': 'order_items'},
        ),
        migrations.AlterField(
            model_name='itemaddition',
            name='addition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemaddition_addition', to='orders.Addition'),
        ),
        migrations.AlterField(
            model_name='itemaddition',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemaddition_item', to='orders.Item'),
        ),
        migrations.AlterField(
            model_name='itemtopping',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemtopping_item', to='orders.Item'),
        ),
        migrations.AlterField(
            model_name='itemtopping',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemtopping_topping', to='orders.Topping'),
        ),
    ]
