# Generated by Django 2.2.5 on 2019-10-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
